name: Main

on:
  push:
    branches: ["main"]

env:
  GO_VERSION: "1.24.3"

jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install Go dependencies
        run: go get ./...
        working-directory: ./test-server
      - name: Build Test Pocketbase Server
        run: go build -v ./...
        working-directory: ./test-server
      - uses: swift-actions/setup-swift@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: |
          cd ./test-server && go run . serve --dir="./test_pb_data" &
          sleep 10 && swift test -v